version: '3'

services:

  web:
      container_name: ${PROJECT_NAME}_web
      build: .
      working_dir: /code
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - '8085:8000'
      expose:
        - '8000'
      links:
        - mysql
      networks:
        backend:
          ipv4_address: 192.20.0