# Generated by Django 4.2.6 on 2023-10-28 19:16

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'Este nombre de usuario ya existe.'}, help_text='Rquerido. 30 caracteres o menos. Solo letras, numeros y @/./+/-/_.', max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Nombre de usuario')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electronico')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.IntegerField(choices=[(1, 'Usuario normal'), (2, 'Psicólogo')], default=1, verbose_name='Tipo de usuario')),
                ('document', models.CharField(max_length=20, unique=True, verbose_name='N° de Documento')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(default='lnnUb0w3lNQQ', max_length=10, unique=True)),
                ('clients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.psychologist')),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('form_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('salud', models.IntegerField()),
                ('economia', models.IntegerField()),
                ('trabajo', models.IntegerField()),
                ('romance', models.IntegerField()),
                ('crecimiento_personal', models.IntegerField()),
                ('amigos', models.IntegerField()),
                ('diversion', models.IntegerField()),
                ('imagen_propia', models.IntegerField()),
                ('ambiente_fisico', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('message', models.TextField(max_length=200, null=True)),
                ('message_title', models.TextField(max_length=30, null=True)),
                ('img', models.ImageField(null=True, upload_to='wheels/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
