# Generated by Django 4.2.5 on 2023-10-01 18:50

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import user.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('second_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25)),
                ('second_last_name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Por favor ingresar una dirección de email válida')])),
                ('user_creation', models.DateField(default=datetime.date(2023, 10, 1))),
                ('password', models.CharField(max_length=16, validators=[user.custom_validators.PasswordValidator])),
            ],
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('form_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('healthy', models.IntegerField()),
                ('economy', models.IntegerField()),
                ('job', models.IntegerField()),
                ('romance', models.IntegerField()),
                ('personal_growth', models.IntegerField()),
                ('friends', models.IntegerField()),
                ('fun', models.IntegerField()),
                ('self_image', models.IntegerField()),
                ('phy_envio', models.IntegerField()),
                ('date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
