# Generated by Django 4.2.6 on 2023-10-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='img',
            field=models.ImageField(null=True, upload_to='wheels/'),
        ),
        migrations.AddField(
            model_name='forms',
            name='img_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='MerQQ0gOXIqs', max_length=10, unique=True),
        ),
    ]
