# Generated by Django 4.2.5 on 2023-10-03 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_creation',
            field=models.DateField(default=datetime.date(2023, 10, 3)),
        ),
    ]
