# Generated by Django 4.2.6 on 2023-10-14 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='clients',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
