# Generated by Django 4.2.5 on 2023-10-05 00:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import user.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_alter_user_user_creation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Por favor ingresar una dirección de email válida')])),
                ('user_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.CharField(max_length=16, validators=[user.custom_validators.PasswordValidator])),
                ('user_type', models.IntegerField(choices=[(1, 'Usuario normal'), (2, 'Psicólogo')])),
            ],
        ),
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clients', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='forms',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
