# Generated by Django 4.2.6 on 2023-10-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userbase_email_alter_userbase_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='EwV6KV2QcP', max_length=10),
        ),
    ]
