# Generated by Django 4.2.5 on 2023-10-05 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_psychologist_alter_forms_user_id_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
