# Generated by Django 4.2.5 on 2023-10-07 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_myuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forms',
            old_name='phy_envio',
            new_name='ambiente_fisico',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='friends',
            new_name='amigos',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='personal_growth',
            new_name='crecimiento_personal',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='healthy',
            new_name='diversion',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='economy',
            new_name='economia',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='fun',
            new_name='imagen_propia',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='job',
            new_name='salud',
        ),
        migrations.RenameField(
            model_name='forms',
            old_name='self_image',
            new_name='trabajo',
        ),
        migrations.AlterField(
            model_name='forms',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
