# Generated by Django 4.2.6 on 2023-10-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_psychologist_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='qpkZxyR54b', max_length=10),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electronico'),
        ),
    ]
