# Generated by Django 4.2.6 on 2023-10-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_psychologist_code_alter_userbase_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='8gDcGeTRSztT', max_length=10, unique=True),
        ),
    ]
