# Generated by Django 4.2.6 on 2023-10-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_psychologist_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='message',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='A7Ul5qTrTQG4', max_length=10, unique=True),
        ),
    ]
