# Generated by Django 4.2.6 on 2023-10-21 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_forms_message_alter_psychologist_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='message_title',
            field=models.TextField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='mQ7e9zVifxe2', max_length=10, unique=True),
        ),
    ]
