# Generated by Django 4.2.6 on 2023-10-22 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_forms_message_title_alter_psychologist_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='document',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='PjkJPqWcUuKE', max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('req_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('result', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.psychologist')),
            ],
        ),
    ]
