# Generated by Django 4.2.6 on 2023-10-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userbase_document_alter_psychologist_code_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='1CvjSRwMKKt8', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='document',
            field=models.CharField(max_length=20),
        ),
    ]
