# Generated by Django 4.2.6 on 2023-10-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_psychologist_code_alter_userbase_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='wCz1yKBo3r15', max_length=10, unique=True),
        ),
    ]
