# Generated by Django 4.2.6 on 2023-10-22 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_psychologist_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='V4SuCPLi8ebz', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userbase',
            name='document',
            field=models.CharField(max_length=20, unique=True, verbose_name='N° de Documento'),
        ),
    ]
