# Generated by Django 4.2.6 on 2023-10-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_psychologist_code_alter_userbase_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='code',
            field=models.CharField(default='aPV9NpqF4QGT', max_length=10, unique=True),
        ),
    ]
